export const CALCULATION_CONSTANTS = {
    DEFAULT_PRECISION: 4,
    CURRENCY_PRECISION: 2,
    PERCENTAGE_PRECISION: 2,
    MAX_CALCULATION_TIME_MS: 5000,
    CALCULATION_TIMEOUT_ERROR: 'Calculation timeout exceeded',
};